// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nbdaxpgnfysquicnllmm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5iZGF4cGduZnlzcXVpY25sbG1tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5NjE2ODIsImV4cCI6MjA3MTUzNzY4Mn0.X1OujUA8H0Df9tWZZEIkAX5_yJ6GiCdOO4w8wvS3BOA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});